version: '3.4'
x-extra-hosts: &extra_hosts
  - "tinypc-server:192.168.1.34"
services:
  transmission-openvpn:
    extra_hosts: *extra_hosts
    cap_add:
      - NET_ADMIN
    volumes:
      - '/server/datapath/transmission:/data'
      - '/dev/net/tun:/dev/net/tun'
    environment:
      - OPENVPN_PROVIDER=WINDSCRIBE
      - OPENVPN_CONFIG=France-tcp
      - OPENVPN_USERNAME=<user>
      - OPENVPN_PASSWORD=<pass>
      - LOCAL_NETWORK=192.168.1.0/24
      - TZ=Europe/Madrid
      - 'TRANSMISSION_BIND_ADDRESS_IPV4=192.168.1.34'
      - 'TRANSMISSION_RPC_WHITELIST=127.0.0.1,192.168.*.*'
      - 'TRANSMISSION_RPC_HOST_WHITELIST=127.0.0.1,192.168.*.*'
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - '9091:9091'
    restart: unless-stopped
    image: haugene/transmission-openvpn
  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    extra_hosts: *extra_hosts
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - UMASK_SET=022
    volumes:
      - '/server/datapath/sonarr:/config'
      - '/server/datapath/nas/Series:/tv'
      - '/server/datapath/transmission:/downloads'
      - '/server/datapath/transmission/completed:/data/completed'
    ports:
      - '8989:8989'
    restart: unless-stopped
  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    extra_hosts: *extra_hosts
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - UMASK_SET=022
    volumes:
      - '/server/datapath/radarr:/config'
      - '/server/datapath/nas/Movies:/movies'
      - '/server/datapath/transmission:/downloads'
      - '/server/datapath/transmission/completed:/data/completed'
    ports:
      - '7878:7878'
    restart: unless-stopped
  jackett:
    image: ghcr.io/linuxserver/jackett
    container_name: jackett
    extra_hosts: *extra_hosts
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - AUTO_UPDATE=false
    volumes:
      - '/server/datapath/jackett:/config'
      - '/server/datapath/downloads:/downloads'
    ports:
      - '9117:9117'
    restart: unless-stopped
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    extra_hosts: *extra_hosts
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - UMASK_SET=022 #optional
      - PLEX_CLAIM= #optional
    volumes:
      - /server/datapath/plex:/config
      - /server/datapath/nas/Series:/tv
      - /server/datapath/nas/Movies:/movies
    ports:
     - 32400:32400
     - 1900:1900
     - 3005:3005
     - 5353:5353
     - 8324:8324
     - 32469:32469
    restart: unless-stopped
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    extra_hosts: *extra_hosts
    volumes:
      - '/server/datapath:/srv'
      - '/server/datapath/filebrowser/filebrowser.db:/database.db'
      - '/server/datapath/filebrowser/filebrowser.json:/.filebrowser.json'
    ports:
      - '9090:8080'
