version: '3.4'
x-extra-hosts: &extra_hosts
  - "tinypc-server:${IP_ADDRESS}"
x-env_file: &env_file
  - environment
services:
  transmission-openvpn:
    extra_hosts: *extra_hosts
    env_file: *env_file
    cap_add:
      - NET_ADMIN
    volumes:
      - '${DATA_PATH}/transmission:/data'
    environment:
      - OPENVPN_PROVIDER=WINDSCRIBE
      - OPENVPN_CONFIG=France-tcp
      - OPENVPN_USERNAME=${OPENVPN_USERNAME}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - LOCAL_NETWORK=${LOCAL_NETWORK}
      - TZ=${TIMEZONE}
      - 'TRANSMISSION_BIND_ADDRESS_IPV4=${IP_ADDRESS}'
      - 'TRANSMISSION_RPC_WHITELIST=127.0.0.1,192.168.*.*'
      - 'TRANSMISSION_RPC_HOST_WHITELIST=127.0.0.1,192.168.*.*'
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - '9091:9091'
    restart: unless-stopped
    image: haugene/transmission-openvpn
  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    extra_hosts: *extra_hosts
    env_file: *env_file
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - UMASK_SET=022
    volumes:
      - '${DATA_PATH}/sonarr:/config'
      - '${DATA_PATH}/nas/Series:/tv'
      - '${DATA_PATH}/transmission:/downloads'
      - '${DATA_PATH}/transmission/completed:/data/completed'
    ports:
      - '8989:8989'
    restart: unless-stopped
  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    extra_hosts: *extra_hosts
    env_file: *env_file
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - UMASK_SET=022
    volumes:
      - '${DATA_PATH}/radarr:/config'
      - '${DATA_PATH}/nas/Movies:/movies'
      - '${DATA_PATH}/transmission:/downloads'
      - '${DATA_PATH}/transmission/completed:/data/completed'
    ports:
      - '7878:7878'
    restart: unless-stopped
  jackett:
    image: ghcr.io/linuxserver/jackett
    container_name: jackett
    extra_hosts: *extra_hosts
    env_file: *env_file
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - AUTO_UPDATE=false
    volumes:
      - '${DATA_PATH}/jackett:/config'
      - '${DATA_PATH}/downloads:/downloads'
    ports:
      - '9117:9117'
    restart: unless-stopped
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    extra_hosts: *extra_hosts
    env_file: *env_file
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - UMASK_SET=022 #optional
      - PLEX_CLAIM= #optional
    volumes:
      - ${DATA_PATH}/plex:/config
      - ${DATA_PATH}/nas/Series:/tv
      - ${DATA_PATH}/nas/Movies:/movies
    ports:
     - 32400:32400
    restart: unless-stopped
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    extra_hosts: *extra_hosts
    env_file: *env_file
    volumes:
      - '${DATA_PATH}:/srv'
      - '${DATA_PATH}/filebrowser/filebrowser.db:/database.db'
      - '${DATA_PATH}/filebrowser/filebrowser.json:/.filebrowser.json'
    ports:
      - '9090:8080'
